### ISSUE TITLE
ikona power=line

### ISSUE THREAD

**Issue by kaylesk** [FreemapSlovakia/MapsforgeFreemapHikingStyle#1]
Zbytočne veľká ikona na power=line. O niečo zmenšiť a možno častejšie opakovanie.

**Comment by zdila** [comment]
Ikony by mohli byt len na powe=pole / power=tower.

**Comment by kaylesk** [comment]
power=tower bude mať ikonku - c7f8be014589f960ac1ed3d887afcbfd46dec2ed
