### ISSUE TITLE
Renderovať doliny a horské hrebene.

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/MapsforgeFreemapHikingStyle#10]
Renderovať natural=valley a natural=ridge - ich názvy na way, a node.

**Comment by hyriak** [comment]
Bolo by to fajn nemuselo by sa zadávať place=locality, ale asi by to chcelo zobrazovať len v určitých layers aby bol v tom prehľad.

**Comment by kaylesk** [comment]
Generátor už obsahuje tieto tagy 3da4bd0 (po 20.1.2017 budú v mape) takže otázka ako na to?
Obávam sa, že tie way budú krátke aby boli vykreslené iba ako text pri menšom z.
Dať tam nejakú čiaru, niečo ako v prílohe?
![screenshot_20170117-122051](https://cloud.githubusercontent.com/assets/8353866/22018515/79b45aee-dcaf-11e6-9395-5f6d2f7c8632.png)

**Comment by tjamecny** [comment]
V DiSKu som to dal na z15/z16 s tým, že ak sa názov nezmestí celý, tak sa proste nezobrazí. Čiaru by som tam nedával, lebo sa niekto pozastaví nad tým, že čo má znamenať, keďže v realite tam nič nie je. Inak je podľa mna zbytočné to robiť pre node, pretože výskyt bol:
- 1 bod pre valley
- 2 body (aj to mimo územia SK) pre ridge (alebo naopak).

Pokiaľ niekto nevie nakresliť cestu (napr. podľa vrstevníc), môže to otagovať ako place=locality ;)

**Comment by hyriak** [comment]
Čiaru nakresliť nie je problém. Akurát nazov doliny sa nezobrazoval, tak preto place:locality. Uvidíme v piatok. A zmazem locality duplicity.

**Comment by kaylesk** [comment]
Tak teda v dev štýle to je použité,. Ešte som dnes mierne upravil veľkosti a farby - 275268a. Ak nebudú námietky budem pokladať za vybavené.

**Comment by hyriak** [comment]
Áno je to viac ok. Zatial som xml-ko nepozeral či by sa nedalo, na spôsob papierovej mapy,  nie opakovanie ale rozložiť to na celú ciaru. - Už viem prečo som dával place:locality nakoľko si raz za polrok tlačím mapu cez mobac od freemap.sk tak tam sa doliny nezobrazujú. Ak viete ako inak stiahnuť rendrovanu mapu. Dajte vediet.

**Comment by kaylesk** [comment]
Treba mať na pamäti ze mapsforge to musí vykresľovať "za jazdy", takže určité veci budú zjednodušené. A také čosi momentálne nie je realizovateľné. (i pravdu povediac som pozeral len zbežne, či je niečo také možné)

A ešte by som doplnil, že uvedené názvy budú aj na webe https://github.com/FreemapSlovakia/FreemapDiSK/issues/16

**Comment by kaylesk** [comment]
Žiadne väčšie námietky, tak teda zatváram.
