### ISSUE TITLE
publikovať bigslovakia-latest

### ISSUE THREAD

**Issue by MichalPP** [FreemapSlovakia/MapsforgeFreemapHikingStyle#13]
momentálne máme súbor bigslovakia$datum.pbf uložený v neprístupnej časti servera. zle sa potom debugujú veci.

navrhuje do download.freemap.sk niekam dať bigslovakia-latest.pbf ktorý by bol verejne dostupný a najaktualnejší.

**Comment by kaylesk** [comment]
Asi nie moc vhodné miesto, pre Locus mapu používam extrakt z geofabrik.
