### ISSUE TITLE
Banské haldy (landuse=quarry)

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/MapsforgeFreemapHikingStyle#14]
V tejto oblasti sa nachádza veľké množstvo banských háld otagovaných ako landuse=quarry
http://www.openstreetmap.org/#map=17/48.96350/19.51362&layers=N
V téme sú však neni renderované. Iba názov je vidno.

**Comment by kaylesk** [comment]
Tieto quarry sú zakreslené "len tak" (nie je to multipolygon). A keďže sú definované v štýle skôr prekryje ich les.
Tak či tak les by mal byť prvý pre istotu, takže to preskupím.

**Comment by kaylesk** [comment]
Opravené v commit-e 9473fac a každú chvíľu bude aj nové vydanie štýlu.

**Comment by seg-on** [comment]
updatoval som jak mapu tak štýl ale vyzerá že je to rovnaké :/

**Comment by kaylesk** [comment]
A aké je priblíženie? Niektoré sú dosť malé.
![screenshot_20170223-075545](https://cloud.githubusercontent.com/assets/8353866/23248021/8ba62da8-f99d-11e6-9d16-145bdc4b627e.png)

Ešte možno skúsiť vymazať cache, aj keď sa obrázok výplne nemenil
Nastavenia > Rôzne > Vymazať dočasné údaje > Dočasné súbory (priečinok 'cache')

**Comment by seg-on** [comment]
Ahoj.
Dík asi bola chyba na mojej strane skúšal som všeličo možné a rozbehlo sa to.
Mám podozrenie že sa mi prepla téma na vývojovú pri update. zmazal som ju reštartol locus a všetko ide ako má :)
