### ISSUE TITLE
Vykresľovanie  barrier=swing_gate

### ISSUE THREAD

**Issue by hyriak** [FreemapSlovakia/MapsforgeFreemapHikingStyle#15]
Vykresľovanie  barrier=swing_gate pri v stupe do lesa. V dátovom súbore asi dáta nie sú stiahnuté. Pri zobrazení by to mohlo byť kľudne aj barrier-lift_gate.svg

**Comment by kaylesk** [comment]
Po najbližšej aktualizácií mapy a hlavne štýlu sa už budú zobrazovať. Zatiaľ rovnako ako lift_gate.
