### ISSUE TITLE
tourism:wilderness_hut

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/MapsforgeFreemapHikingStyle#16]
Nezobrazuje tourism=wilderness_hut, tourism=alpine_hut.

**Comment by kaylesk** [comment]
Zatiaľ pridané do generovanie, neskôr pribudnú aj ikonky.

**Comment by kaylesk** [comment]
Ešte k ikonám, niečo podobné ako má OSM mapnik bude stačiť? 
https://github.com/openstreetmap/mapnik-stylesheets/tree/master/symbols

**Comment by seg-on** [comment]
jasné tá ikonka čo má OSM mapnik je super

**Comment by kaylesk** [comment]
Nová mapa so štýlom už zobrazuje tieto POI.
Ikonka nie je rovnaká, ale dosť podobná (asi sa aj budú pliesť) viď nižšie.
https://github.com/FreemapSlovakia/MapsforgeFreemapHikingStyle/blob/master/client/freemap_slovakia/symbols/alpine_hut.svg
https://github.com/FreemapSlovakia/MapsforgeFreemapHikingStyle/blob/master/client/freemap_slovakia/symbols/wilderness_hut.svg

Ak by bolo treba ešte niečo doladiť, stačí znova otvoriť chybu.

**Comment by seg-on** [comment]
Hej ikonky sú podobné, ale podstatné je že sa už zobrazujú.
rozdiel v tagoch by mal byť že alpine_hut je platená horská chata a wildness_hut voľne prístupná.
Takže ma napadá že ikonky rozlíšiť farebne aj farebne.
Platená by bola mohla byť hnedá.
