### ISSUE TITLE
Poupraviť štýl railway=narrow_gauge

### ISSUE THREAD

**Issue by seg-on** [FreemapSlovakia/MapsforgeFreemapHikingStyle#23]
šedá čiara pre úzkokolajku je relatívne nevýrazná vo Freemap štýle a tiež skorej nabáda človeka že sa jedná o nejaký typ cesty.
Čo keby sa striedalo pruhovanie ako na železnici ale namiesto bielej by bola šedá? 
Takže šedo-čierne pruhovanie.

**Comment by kaylesk** [comment]
Upravil som aj bežnú železnicu, je viac čierno/biela a narrow_gauge aj funicular sú čierno/šedasté.
Tiež pribudla chýbajúca preserved, je čierno/žltá (treba dáta z 18.5.)
Je to zverejnené v TEST štýle v plugine alebo na stiahnutie tu http://freemap.kayle.sk/locus/ (treba ísť z mobilu)

**Comment by kaylesk** [comment]
Toto by som zavrel, commit 35eab6e95e63f9a33cdb37d010eeed71a0cc208c zmenil niektoré veci a neboli odvtedy pripomienky
