### ISSUE TITLE
Nezobrazujú sa názvy autobusových zastávok

### ISSUE THREAD

**Issue by brtani** [FreemapSlovakia/MapsforgeFreemapHikingStyle#25]
Nie som si istý či sa jedná o chybu. Používam Locus s addonom freemap a nezobrazujú sa mi názvy autobusových zastávok. Na stránke freemap sa mi zobrazujú, ak si zobrazim mapu cez openstreetmap

**Comment by kaylesk** [comment]
Je to chyba. V štýle nie je definované použitie tag-u name (názov), takže nemá čo zobraziť.
