### ISSUE TITLE
rendrovanie tourist=attraction nezobrazuje text, len ikonu

### ISSUE THREAD

**Issue by misko903** [FreemapSlovakia/MapsforgeFreemapHikingStyle#27]
Ikonu zltej hviezdy. Mozno je hviezda prilis velka?

**Comment by kaylesk** [comment]
Pri minulých úpravách, keď sa menili popisky z jednotného značenia na samostatné podľa druhu POI (aby boli rôzne farebné/veľké) pre attraction nebol popisok pridaný.

**Comment by kaylesk** [comment]
bude opravené - 64b2a8f71c45bf9e80241fa32828d5c5bd1d2ac4
