### ISSUE TITLE
Renterovat krmelec

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/MapsforgeFreemapHikingStyle#5]
Renterovat krmelec

**Comment by kaylesk** [comment]
Mapa po 26.6.2016 už bude obsahovať amenity=feeding_place.
Ešte otázka. Rovnakú ikonku aj na dať aj building=hayloft? Ten sa už dávno pridáva, len sa zobrazuje ako bežná budova.

**Comment by zdila** [comment]
Hayloft by som neriesil.

**Comment by kaylesk** [comment]
vyriešené

**Comment by zdila** [comment]
Bol este navrh renderovat to pre amenity=game_feeding ktorych je vraj viac.
