### ISSUE TITLE
vykreslenie bodových prekážok - barrier

### ISSUE THREAD

**Issue by kaylesk** [FreemapSlovakia/MapsforgeFreemapHikingStyle#7]
Momentálne je v generátore iba barrier=bollard a barrier=cycle_barrier
Štýl ale obsahuje iba barrier=bollard

Tiež by bolo dobré pridať block, lift_gate, gate, entrance.

City_wall, wall a fence sa vykresľujú

**Comment by hyriak** [comment]
Sevas ešte ma napadlo aj  **barrier=swing_gate** pri v stupe do lesa. V dátovom súbore asi dáta nie sú stiahnuté. Pri zobrazení by to mohlo byť kľudne aj barrier-lift_gate.svg
