### ISSUE TITLE
Vykreslovanie pozemnej lanovej drahy

### ISSUE THREAD

**Issue by hyriak** [FreemapSlovakia/MapsforgeFreemapHikingStyle#8]
Všimol som si že na Hrebienok  a v Jasnej sa nezobrazujú pozemné lanovky  railway=funicular.

**Comment by hyriak** [comment]
tak po preštudovaní osm freemap   tak som tam nenašiel dáta o pozemnej lanovej dráhe railway=funicular  asi by to chcelo doplniť pri generovaní Freemap Slovankia Topo.

**Comment by kaylesk** [comment]
Od 14.10.2016 generované dáta obsahujú uvedený tag.
Ešte to ostáva pridať do renderovacích pravidiel.

**Comment by hyriak** [comment]
OK, už ich vidím / lebo som sa  hral s pravidlami./ Vďaka.

**Comment by hyriak** [comment]
Asi pri update sa zabudlo na funicular?

<rule e="way" k="railway" v="rail|funicular">
   <line stroke="#000000" stroke-width="0.8dp" stroke-linecap="butt"/>
</rule>

**Comment by kaylesk** [comment]
Tak je, zavreté som veru nepozeral.
