### ISSUE TITLE
Vykresľovanie štôlni  resp. baní

### ISSUE THREAD

**Issue by hyriak** [FreemapSlovakia/MapsforgeFreemapHikingStyle#9]
Bolo by možné  doplniť dátový súbor o 
**Tag:man_made=adit**

a pridať značku:
http://wiki.openstreetmap.org/wiki/Cs:Tag:man_made%3Dadit
- aspoň čo viem "mapnik" to nevykresľuje, 

- ak by sa dali vygenerovať len data, tak by som sa pohral s xml-kom na zobrazenie. 
Ďik.

**Comment by kaylesk** [comment]
man_made=adit (ale aj man_made=mineshaft) sa generujú do mapových dát (tag-mapping-fm.xml) a mali by sa aj zobrazovať od z14. Dokonca sa rozlišuje či má disused=yes.
https://github.com/FreemapSlovakia/MapsforgeFreemapHikingStyle/blob/master/client/freemap_slovakia/symbols/adit.svg
https://github.com/FreemapSlovakia/MapsforgeFreemapHikingStyle/blob/master/client/freemap_slovakia/symbols/adit2.svg

Treba skúsiť viac priblížiť, či sa neschová ikonka pre nejaký iný objekt.

**Comment by hyriak** [comment]
Vďaka nevšimol som si to v xml. Po udate dát je to v poriadku
